[package]
name = "json-prob-parser"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "json_prob_parser"
path = "src/lib.rs"

[[bin]]
name = "json-prob-parser"
path = "src/bin/json-prob-parser.rs"

[dependencies]

